### ISSUE TITLE
Modify checkov checks

### ISSUE THREAD

**Issue by vladimirobucina** [NovoNordisk-OpenSource/r.workflows#9]
We're running into with `checkov` check:

```
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
```

We need to change something, probably permissions in the workflow inside repo.

**Comment by akselthomsen** [comment]
Issue is related to the permissions set in the `check_and_co.yaml` file in the repository using the workflows.
The default permissions in `write-all` which is what `checkov` is warning against.

Solve by setting the permissions in the workflow to:

```
permissions:
  contents: write
  pull-requests: write
```

In #11  I have updated the snippet in the readme to reflect this, and removed unnecessary permissions in the megaliter workflow.

**Comment by vladimirobucina** [comment]
sounds great! tnx! :)
